---
###
#
# Ansible Connection & General Configuration Section
#
###

ansible_connection: ssh
ansible_ssh_host:    # edit here for IP address of ISLE Host Server or local VM e.g. 192.168.1.100
ansible_ssh_user:   # edit here for deploy user e.g. vagrant
user_name: islandora
pub_locale: ~/Users/enduser/.ssh/id_rsa.pub # edit here for local enduser id_rsa.pub path
user_password:  islandora
user_shell: /bin/bash
group_id_number: 10000
user_id_number: 10000


isle_repo: https://github.com/Islandora-Collaboration-Group/ISLE.git
isle_repo_path: /opt/ISLE

### Docker

docker_version: 'ce'
docker_package: "docker-{{ docker_version }}"

docker_user: islandora

### Docker-Compose

docker_compose_version: "1.25.4"
docker_compose_url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
docker_compose_path: /usr/local/bin/docker-compose

### ISLE Images
# Commented out images are optional

isle_image_repos:
  - isle-apache
  - isle-mysql
  - isle-tomcat
  - isle-solr
  - isle-imageservices
  - isle-fedora
  #- isle-varnish
  #- isle-blazegraph

isle_docker_image_tag: 1.4.2


### For Debian / Ubuntu Hosts
docker_apt_repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_type }}"
docker_apt_release_type: stable

### For RHEL / CentOS Hosts

docker_yum_repo: https://download.docker.com/linux/centos/docker-{{ docker_version }}.repo
